version: "3.8"
services:
    conda-with-requirements:        
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - "8888:8888"
        volumes:
            - "./notebooks:/opt/notebooks"
            - "./data:/opt/notebooks/data"
        entrypoint: /bin/bash
        command: -c "/opt/conda/bin/jupyter notebook --notebook-dir=/opt/notebooks --ip='*' --port=8888 --no-browser --allow-root" 