version: "3.8"
services:
    anaconda:
        image: miklt/ml-docker
        ports:
            - "8888:8888"
        volumes:
            - "./dados:/opt/notebooks"
        entrypoint: /bin/bash

        command: -c "/opt/conda/bin/conda install jupyter -y --quiet && /opt/conda/bin/jupyter notebook --notebook-dir=/opt/notebooks --ip='*' --port=8888 --no-browser --allow-root"